import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from "@/app/provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (

        <html lang="en" className={"dark text-foreground bg-background"} suppressHydrationWarning={true}>
        <body className={inter.className}>
        <Providers>
                {children}
        </Providers>
        <SpeedInsights/>
        </body>
        </html>
    )
}
